{
  "patcher": {
    "fileversion": 1,
    "appversion": {"major": 9, "minor": 1, "revision": 4, "architecture": "x64", "modernui": 1},
    "classnamespace": "box",
    "rect": [40, 40, 1500, 1220],
    "gridsize": [15, 15],
    "openinpresentation": 1,
    "description": "Standalone Pose interaction profiles calibration and safety demo.",
    "tags": "pose interaction singer instrumentalist calibration midi demo",
    "boxes": [
      {"box": {"id": "demo-top-panel", "maxclass": "panel", "numinlets": 1, "numoutlets": 0, "patching_rect": [20, 15, 1240, 95], "presentation": 1, "presentation_rect": [20, 15, 1240, 95], "background": 1, "bgcolor": [0.16, 0.24, 0.2, 1]}},
      {"box": {"id": "demo-title", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [40, 28, 520, 26], "text": "GEEHON POSE INTERACTION PROFILES", "fontsize": 18, "presentation": 1, "presentation_rect": [40, 28, 520, 26], "textcolor": [0.94, 0.96, 0.93, 1]}},
      {"box": {"id": "demo-subtitle", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [40, 62, 560, 22], "text": "Calibrated body features / safe tracking loss / optional foot clutch", "presentation": 1, "presentation_rect": [40, 62, 560, 22], "textcolor": [0.72, 0.8, 0.75, 1]}},
      {"box": {"id": "demo-profile-label", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [655, 34, 65, 22], "text": "Profile", "presentation": 1, "presentation_rect": [655, 34, 65, 22], "textcolor": [0.94, 0.96, 0.93, 1]}},
      {"box": {"id": "demo-profile", "maxclass": "umenu", "numinlets": 1, "numoutlets": 3, "outlettype": ["int", "", ""], "items": ["Singer", ",", "Instrumentalist"], "parameter_enable": 0, "patching_rect": [725, 34, 180, 22], "varname": "pose_demo_profile", "hint": "Choose an independently calibrated Singer or Instrumentalist baseline", "presentation": 1, "presentation_rect": [725, 34, 180, 22]}},
      {"box": {"id": "demo-arm-label", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [930, 34, 42, 22], "text": "Arm", "presentation": 1, "presentation_rect": [930, 34, 42, 22], "textcolor": [0.94, 0.96, 0.93, 1]}},
      {"box": {"id": "demo-arm", "maxclass": "toggle", "numinlets": 1, "numoutlets": 1, "outlettype": ["int"], "parameter_enable": 0, "patching_rect": [975, 32, 26, 26], "varname": "pose_demo_arm", "hint": "Arm or intentionally release body control with an 80 ms ramp", "presentation": 1, "presentation_rect": [975, 32, 26, 26]}},
      {"box": {"id": "demo-calibrate-label", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [1030, 34, 70, 22], "text": "Calibrate", "presentation": 1, "presentation_rect": [1030, 34, 70, 22], "textcolor": [0.94, 0.96, 0.93, 1]}},
      {"box": {"id": "demo-calibrate", "maxclass": "button", "numinlets": 1, "numoutlets": 1, "outlettype": ["bang"], "parameter_enable": 0, "patching_rect": [1105, 32, 26, 26], "varname": "pose_demo_calibrate", "hint": "Capture a 3 second neutral baseline for the selected profile", "presentation": 1, "presentation_rect": [1105, 32, 26, 26]}},

      {"box": {"id": "demo-camera", "maxclass": "bpatcher", "name": "mt_control_pose_jweb.maxpat", "numinlets": 0, "numoutlets": 4, "outlettype": ["", "", "", ""], "patching_rect": [30, 140, 454, 440], "presentation": 1, "presentation_rect": [30, 130, 454, 440], "offset": [0, 0], "border": 1, "clickthrough": 0, "enablehscroll": 0, "enablevscroll": 0, "lockeddragscroll": 0, "varname": "pose_demo_camera", "hint": "Camera, mirrored preview, skeleton, and control-zone source"}},
      {"box": {"id": "demo-midi", "maxclass": "bpatcher", "name": "mt_midi_clutch.maxpat", "numinlets": 0, "numoutlets": 4, "outlettype": ["", "", "", ""], "patching_rect": [510, 140, 700, 130], "presentation": 1, "presentation_rect": [510, 130, 700, 130], "offset": [0, 0], "border": 1, "clickthrough": 0, "enablehscroll": 0, "enablevscroll": 0, "lockeddragscroll": 0, "varname": "pose_demo_midi"}},

      {"box": {"id": "demo-status-panel", "maxclass": "panel", "numinlets": 1, "numoutlets": 0, "patching_rect": [510, 285, 700, 285], "presentation": 1, "presentation_rect": [510, 280, 700, 290], "background": 1, "bgcolor": [0.95, 0.97, 0.95, 1], "bordercolor": [0.62, 0.72, 0.66, 1]}},
      {"box": {"id": "demo-status-title", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [535, 300, 240, 24], "text": "INTERACTION STATUS", "fontsize": 15, "presentation": 1, "presentation_rect": [535, 298, 240, 24]}},
      {"box": {"id": "demo-state-label", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [535, 340, 75, 22], "text": "State", "presentation": 1, "presentation_rect": [535, 338, 75, 22]}},
      {"box": {"id": "demo-state", "maxclass": "message", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [620, 340, 145, 22], "text": "NO_CAMERA", "varname": "pose_demo_state", "hint": "Current safe interaction state", "presentation": 1, "presentation_rect": [620, 338, 145, 22]}},
      {"box": {"id": "demo-confidence-label", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [795, 340, 95, 22], "text": "Confidence", "presentation": 1, "presentation_rect": [795, 338, 95, 22]}},
      {"box": {"id": "demo-confidence", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": ["", "bang"], "minimum": 0, "maximum": 1, "patching_rect": [895, 340, 80, 22], "varname": "pose_demo_confidence", "hint": "Median confidence of core body landmarks", "presentation": 1, "presentation_rect": [895, 338, 80, 22]}},
      {"box": {"id": "demo-pedal-label", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [995, 340, 60, 22], "text": "Pedal", "presentation": 1, "presentation_rect": [995, 338, 60, 22]}},
      {"box": {"id": "demo-pedal-status", "maxclass": "message", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [1055, 340, 125, 22], "text": "optional", "varname": "pose_demo_pedal_status", "hint": "MIDI foot clutch device and learn status", "presentation": 1, "presentation_rect": [1055, 338, 125, 22]}},

      {"box": {"id": "demo-calibrated-label", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [535, 395, 90, 22], "text": "Calibrated", "presentation": 1, "presentation_rect": [535, 393, 90, 22]}},
      {"box": {"id": "demo-calibrated", "maxclass": "toggle", "numinlets": 1, "numoutlets": 1, "outlettype": ["int"], "parameter_enable": 0, "patching_rect": [630, 393, 24, 24], "varname": "pose_demo_calibrated", "hint": "Selected profile has a stored neutral baseline", "presentation": 1, "presentation_rect": [630, 391, 24, 24]}},
      {"box": {"id": "demo-tracking-label", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [685, 395, 70, 22], "text": "Tracking", "presentation": 1, "presentation_rect": [685, 393, 70, 22]}},
      {"box": {"id": "demo-tracking", "maxclass": "toggle", "numinlets": 1, "numoutlets": 1, "outlettype": ["int"], "parameter_enable": 0, "patching_rect": [760, 393, 24, 24], "presentation": 1, "presentation_rect": [760, 391, 24, 24]}},
      {"box": {"id": "demo-zone-label", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [815, 395, 45, 22], "text": "Zone", "presentation": 1, "presentation_rect": [815, 393, 45, 22]}},
      {"box": {"id": "demo-zone", "maxclass": "toggle", "numinlets": 1, "numoutlets": 1, "outlettype": ["int"], "parameter_enable": 0, "patching_rect": [865, 393, 24, 24], "varname": "pose_demo_zone", "hint": "Shoulder and hip centers are inside the control zone", "presentation": 1, "presentation_rect": [865, 391, 24, 24]}},
      {"box": {"id": "demo-active-label", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [920, 395, 50, 22], "text": "Active", "presentation": 1, "presentation_rect": [920, 393, 50, 22]}},
      {"box": {"id": "demo-active", "maxclass": "toggle", "numinlets": 1, "numoutlets": 1, "outlettype": ["int"], "parameter_enable": 0, "patching_rect": [975, 393, 24, 24], "presentation": 1, "presentation_rect": [975, 391, 24, 24]}},
      {"box": {"id": "demo-clutch-label", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [1030, 395, 55, 22], "text": "Clutch", "presentation": 1, "presentation_rect": [1030, 393, 55, 22]}},
      {"box": {"id": "demo-clutch", "maxclass": "toggle", "numinlets": 1, "numoutlets": 1, "outlettype": ["int"], "parameter_enable": 0, "patching_rect": [1090, 393, 24, 24], "presentation": 1, "presentation_rect": [1090, 391, 24, 24]}},

      {"box": {"id": "demo-model-label", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [535, 450, 50, 22], "text": "Model", "presentation": 1, "presentation_rect": [535, 448, 50, 22]}},
      {"box": {"id": "demo-model", "maxclass": "toggle", "numinlets": 1, "numoutlets": 1, "outlettype": ["int"], "parameter_enable": 0, "patching_rect": [590, 448, 24, 24], "presentation": 1, "presentation_rect": [590, 446, 24, 24]}},
      {"box": {"id": "demo-camera-ready-label", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [650, 450, 65, 22], "text": "Camera", "presentation": 1, "presentation_rect": [650, 448, 65, 22]}},
      {"box": {"id": "demo-camera-ready", "maxclass": "toggle", "numinlets": 1, "numoutlets": 1, "outlettype": ["int"], "parameter_enable": 0, "patching_rect": [720, 448, 24, 24], "presentation": 1, "presentation_rect": [720, 446, 24, 24]}},
      {"box": {"id": "demo-pose-label", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [780, 450, 70, 22], "text": "Has Pose", "presentation": 1, "presentation_rect": [780, 448, 70, 22]}},
      {"box": {"id": "demo-has-pose", "maxclass": "toggle", "numinlets": 1, "numoutlets": 1, "outlettype": ["int"], "parameter_enable": 0, "patching_rect": [855, 448, 24, 24], "presentation": 1, "presentation_rect": [855, 446, 24, 24]}},

      {"box": {"id": "demo-raw-panel", "maxclass": "panel", "numinlets": 1, "numoutlets": 0, "patching_rect": [30, 600, 1180, 145], "presentation": 1, "presentation_rect": [30, 600, 1180, 145], "background": 1, "bgcolor": [0.95, 0.97, 0.95, 1]}},
      {"box": {"id": "demo-raw-title", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [50, 615, 260, 22], "text": "RAW BODY FEATURES", "fontsize": 14, "presentation": 1, "presentation_rect": [50, 615, 260, 22]}},

      {"box": {"id": "demo-sway-label", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [50, 655, 125, 22], "text": "Torso Sway", "presentation": 1, "presentation_rect": [50, 655, 125, 22]}},
      {"box": {"id": "demo-sway", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": ["", "bang"], "minimum": -1, "maximum": 1, "patching_rect": [50, 685, 90, 22], "presentation": 1, "presentation_rect": [50, 685, 90, 22]}},
      {"box": {"id": "demo-lean-label", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [230, 655, 125, 22], "text": "Torso Lean", "presentation": 1, "presentation_rect": [230, 655, 125, 22]}},
      {"box": {"id": "demo-lean", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": ["", "bang"], "minimum": -1, "maximum": 1, "patching_rect": [230, 685, 90, 22], "presentation": 1, "presentation_rect": [230, 685, 90, 22]}},
      {"box": {"id": "demo-shoulder-label", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [410, 655, 125, 22], "text": "Shoulder Tilt", "presentation": 1, "presentation_rect": [410, 655, 125, 22]}},
      {"box": {"id": "demo-shoulder", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": ["", "bang"], "minimum": -1, "maximum": 1, "patching_rect": [410, 685, 90, 22], "presentation": 1, "presentation_rect": [410, 685, 90, 22]}},
      {"box": {"id": "demo-head-label", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [590, 655, 125, 22], "text": "Head Turn", "presentation": 1, "presentation_rect": [590, 655, 125, 22]}},
      {"box": {"id": "demo-head", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": ["", "bang"], "minimum": -1, "maximum": 1, "patching_rect": [590, 685, 90, 22], "presentation": 1, "presentation_rect": [590, 685, 90, 22]}},
      {"box": {"id": "demo-proximity-label", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [770, 655, 125, 22], "text": "Body Proximity", "presentation": 1, "presentation_rect": [770, 655, 125, 22]}},
      {"box": {"id": "demo-proximity", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": ["", "bang"], "minimum": -1, "maximum": 1, "patching_rect": [770, 685, 90, 22], "presentation": 1, "presentation_rect": [770, 685, 90, 22]}},
      {"box": {"id": "demo-motion-label", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [950, 655, 125, 22], "text": "Motion Energy", "presentation": 1, "presentation_rect": [950, 655, 125, 22]}},
      {"box": {"id": "demo-motion", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": ["", "bang"], "minimum": 0, "maximum": 1, "patching_rect": [950, 685, 90, 22], "presentation": 1, "presentation_rect": [950, 685, 90, 22]}},

      {"box": {"id": "demo-macro-panel", "maxclass": "panel", "numinlets": 1, "numoutlets": 0, "patching_rect": [30, 770, 1180, 135], "presentation": 1, "presentation_rect": [30, 770, 1180, 135], "background": 1, "bgcolor": [0.96, 0.94, 0.84, 1]}},
      {"box": {"id": "demo-macro-title", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [50, 785, 340, 22], "text": "SEMANTIC MACROS / UNASSIGNED", "fontsize": 14, "presentation": 1, "presentation_rect": [50, 785, 340, 22]}},
      {"box": {"id": "demo-energy-label", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [80, 825, 110, 22], "text": "Energy", "presentation": 1, "presentation_rect": [80, 825, 110, 22]}},
      {"box": {"id": "demo-energy", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": ["", "bang"], "minimum": 0, "maximum": 1, "patching_rect": [80, 855, 90, 22], "presentation": 1, "presentation_rect": [80, 855, 90, 22]}},
      {"box": {"id": "demo-space-label", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [350, 825, 110, 22], "text": "Space", "presentation": 1, "presentation_rect": [350, 825, 110, 22]}},
      {"box": {"id": "demo-space", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": ["", "bang"], "minimum": 0, "maximum": 1, "patching_rect": [350, 855, 90, 22], "presentation": 1, "presentation_rect": [350, 855, 90, 22]}},
      {"box": {"id": "demo-texture-label", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [620, 825, 110, 22], "text": "Texture", "presentation": 1, "presentation_rect": [620, 825, 110, 22]}},
      {"box": {"id": "demo-texture", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": ["", "bang"], "minimum": 0, "maximum": 1, "patching_rect": [620, 855, 90, 22], "presentation": 1, "presentation_rect": [620, 855, 90, 22]}},
      {"box": {"id": "demo-transform-label", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [890, 825, 110, 22], "text": "Transform", "presentation": 1, "presentation_rect": [890, 825, 110, 22]}},
      {"box": {"id": "demo-transform", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": ["", "bang"], "minimum": 0, "maximum": 1, "patching_rect": [890, 855, 90, 22], "presentation": 1, "presentation_rect": [890, 855, 90, 22]}},

      {"box": {"id": "demo-engine", "maxclass": "newobj", "numinlets": 2, "numoutlets": 6, "outlettype": ["", "", "", "", "", ""], "patching_rect": [80, 965, 175, 22], "text": "mt_pose_feature_engine"}},
      {"box": {"id": "demo-profile-engine", "maxclass": "newobj", "numinlets": 2, "numoutlets": 7, "outlettype": ["", "", "", "", "", "", ""], "patching_rect": [300, 965, 155, 22], "text": "mt_interaction_profile"}},
      {"box": {"id": "demo-profile-command", "maxclass": "newobj", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [725, 110, 105, 22], "text": "prepend profile"}},
      {"box": {"id": "demo-profile-fanout", "maxclass": "newobj", "numinlets": 1, "numoutlets": 2, "outlettype": ["list", "list"], "patching_rect": [840, 110, 45, 22], "text": "t l l"}},
      {"box": {"id": "demo-arm-command", "maxclass": "newobj", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [975, 110, 85, 22], "text": "prepend arm"}},
      {"box": {"id": "demo-calibrate-command", "maxclass": "message", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [1105, 110, 65, 22], "text": "calibrate"}},
      {"box": {"id": "demo-calibrate-fanout", "maxclass": "newobj", "numinlets": 1, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [1180, 110, 45, 22], "text": "t s s"}},
      {"box": {"id": "demo-clutch-command", "maxclass": "newobj", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [510, 925, 100, 22], "text": "prepend clutch"}},
      {"box": {"id": "demo-pedal-mode-command", "maxclass": "newobj", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [620, 925, 125, 22], "text": "prepend pedal_mode"}},
      {"box": {"id": "demo-pedal-connected-command", "maxclass": "newobj", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [755, 925, 155, 22], "text": "prepend pedal_connected"}},
      {"box": {"id": "demo-pedal-status-set", "maxclass": "newobj", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [920, 925, 75, 22], "text": "prepend set"}},

      {"box": {"id": "demo-final-fanout", "maxclass": "newobj", "numinlets": 1, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [300, 1005, 45, 22], "text": "t a a"}},
      {"box": {"id": "demo-dict-unpack", "maxclass": "newobj", "numinlets": 1, "numoutlets": 15, "outlettype": ["", "", "", "", "", "", "", "", "", "", "", "", "", "", ""], "patching_rect": [520, 1005, 920, 22], "text": "dict.unpack state: calibrated: tracking_valid: inside_control_zone: armed: clutch_gate: model_ready: camera_ready: has_pose: torso_sway: torso_lean: shoulder_tilt: head_turn: body_proximity: motion_energy:"}},
      {"box": {"id": "demo-state-set", "maxclass": "newobj", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [520, 1040, 75, 22], "text": "prepend set"}},
      {"box": {"id": "demo-active-fanout", "maxclass": "newobj", "numinlets": 1, "numoutlets": 2, "outlettype": ["int", "int"], "patching_rect": [300, 1040, 40, 22], "text": "t i i"}},
      {"box": {"id": "demo-confidence-fanout", "maxclass": "newobj", "numinlets": 1, "numoutlets": 2, "outlettype": ["float", "float"], "patching_rect": [350, 1040, 40, 22], "text": "t f f"}},
      {"box": {"id": "demo-energy-fanout", "maxclass": "newobj", "numinlets": 1, "numoutlets": 2, "outlettype": ["float", "float"], "patching_rect": [400, 1040, 40, 22], "text": "t f f"}},
      {"box": {"id": "demo-space-fanout", "maxclass": "newobj", "numinlets": 1, "numoutlets": 2, "outlettype": ["float", "float"], "patching_rect": [450, 1040, 40, 22], "text": "t f f"}},
      {"box": {"id": "demo-texture-fanout", "maxclass": "newobj", "numinlets": 1, "numoutlets": 2, "outlettype": ["float", "float"], "patching_rect": [500, 1070, 40, 22], "text": "t f f"}},
      {"box": {"id": "demo-transform-fanout", "maxclass": "newobj", "numinlets": 1, "numoutlets": 2, "outlettype": ["float", "float"], "patching_rect": [550, 1070, 40, 22], "text": "t f f"}},

      {"box": {"id": "demo-loadbang", "maxclass": "newobj", "numinlets": 1, "numoutlets": 1, "outlettype": ["bang"], "patching_rect": [1250, 925, 65, 22], "text": "loadbang"}},
      {"box": {"id": "demo-init-trigger", "maxclass": "newobj", "numinlets": 1, "numoutlets": 2, "outlettype": ["bang", "bang"], "patching_rect": [1250, 960, 45, 22], "text": "t b b"}},
      {"box": {"id": "demo-init-profile", "maxclass": "message", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [1250, 995, 35, 22], "text": "0"}},
      {"box": {"id": "demo-init-arm", "maxclass": "message", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [1300, 995, 35, 22], "text": "0"}},

      {"box": {"id": "demo-out-dictionary", "maxclass": "outlet", "numinlets": 1, "numoutlets": 0, "patching_rect": [100, 1130, 30, 30], "comment": "final interaction dictionary"}},
      {"box": {"id": "demo-out-active", "maxclass": "outlet", "numinlets": 1, "numoutlets": 0, "patching_rect": [250, 1130, 30, 30], "comment": "active 0/1"}},
      {"box": {"id": "demo-out-confidence", "maxclass": "outlet", "numinlets": 1, "numoutlets": 0, "patching_rect": [400, 1130, 30, 30], "comment": "tracking confidence 0-1"}},
      {"box": {"id": "demo-out-energy", "maxclass": "outlet", "numinlets": 1, "numoutlets": 0, "patching_rect": [560, 1130, 30, 30], "comment": "Energy macro (unassigned)"}},
      {"box": {"id": "demo-out-space", "maxclass": "outlet", "numinlets": 1, "numoutlets": 0, "patching_rect": [710, 1130, 30, 30], "comment": "Space macro (unassigned)"}},
      {"box": {"id": "demo-out-texture", "maxclass": "outlet", "numinlets": 1, "numoutlets": 0, "patching_rect": [860, 1130, 30, 30], "comment": "Texture macro (unassigned)"}},
      {"box": {"id": "demo-out-transform", "maxclass": "outlet", "numinlets": 1, "numoutlets": 0, "patching_rect": [1010, 1130, 30, 30], "comment": "Transform macro (unassigned)"}}
    ],
    "lines": [
      {"patchline": {"source": ["demo-camera", 0], "destination": ["demo-engine", 0], "color": [1, 0.62, 0.24, 1]}},
      {"patchline": {"source": ["demo-camera", 2], "destination": ["demo-engine", 1], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["demo-engine", 0], "destination": ["demo-profile-engine", 0], "color": [1, 0.62, 0.24, 1]}},

      {"patchline": {"source": ["demo-profile", 1], "destination": ["demo-profile-command", 0], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["demo-profile-command", 0], "destination": ["demo-profile-fanout", 0], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["demo-profile-fanout", 1], "destination": ["demo-profile-engine", 1], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["demo-profile-fanout", 0], "destination": ["demo-engine", 1], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["demo-arm", 0], "destination": ["demo-arm-command", 0], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["demo-arm-command", 0], "destination": ["demo-profile-engine", 1], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["demo-calibrate", 0], "destination": ["demo-calibrate-command", 0], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["demo-calibrate-command", 0], "destination": ["demo-calibrate-fanout", 0], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["demo-calibrate-fanout", 1], "destination": ["demo-profile-engine", 1], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["demo-calibrate-fanout", 0], "destination": ["demo-engine", 1], "color": [0.44, 0.72, 1, 1]}},

      {"patchline": {"source": ["demo-midi", 0], "destination": ["demo-clutch-command", 0], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["demo-midi", 1], "destination": ["demo-pedal-mode-command", 0], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["demo-midi", 2], "destination": ["demo-pedal-connected-command", 0], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["demo-midi", 3], "destination": ["demo-pedal-status-set", 0], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["demo-clutch-command", 0], "destination": ["demo-profile-engine", 1], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["demo-pedal-mode-command", 0], "destination": ["demo-profile-engine", 1], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["demo-pedal-connected-command", 0], "destination": ["demo-profile-engine", 1], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["demo-pedal-status-set", 0], "destination": ["demo-pedal-status", 0], "color": [0.44, 0.72, 1, 1]}},

      {"patchline": {"source": ["demo-profile-engine", 0], "destination": ["demo-final-fanout", 0], "color": [1, 0.62, 0.24, 1]}},
      {"patchline": {"source": ["demo-final-fanout", 1], "destination": ["demo-dict-unpack", 0], "color": [1, 0.62, 0.24, 1]}},
      {"patchline": {"source": ["demo-final-fanout", 0], "destination": ["demo-out-dictionary", 0], "color": [1, 0.62, 0.24, 1]}},
      {"patchline": {"source": ["demo-profile-engine", 1], "destination": ["demo-active-fanout", 0], "color": [1, 0.62, 0.24, 1]}},
      {"patchline": {"source": ["demo-active-fanout", 1], "destination": ["demo-active", 0], "color": [1, 0.62, 0.24, 1]}},
      {"patchline": {"source": ["demo-active-fanout", 0], "destination": ["demo-out-active", 0], "color": [1, 0.62, 0.24, 1]}},
      {"patchline": {"source": ["demo-profile-engine", 2], "destination": ["demo-confidence-fanout", 0], "color": [1, 0.62, 0.24, 1]}},
      {"patchline": {"source": ["demo-confidence-fanout", 1], "destination": ["demo-confidence", 0], "color": [1, 0.62, 0.24, 1]}},
      {"patchline": {"source": ["demo-confidence-fanout", 0], "destination": ["demo-out-confidence", 0], "color": [1, 0.62, 0.24, 1]}},

      {"patchline": {"source": ["demo-profile-engine", 3], "destination": ["demo-energy-fanout", 0], "color": [1, 0.62, 0.24, 1]}},
      {"patchline": {"source": ["demo-energy-fanout", 1], "destination": ["demo-energy", 0], "color": [1, 0.62, 0.24, 1]}},
      {"patchline": {"source": ["demo-energy-fanout", 0], "destination": ["demo-out-energy", 0], "color": [1, 0.62, 0.24, 1]}},
      {"patchline": {"source": ["demo-profile-engine", 4], "destination": ["demo-space-fanout", 0], "color": [1, 0.62, 0.24, 1]}},
      {"patchline": {"source": ["demo-space-fanout", 1], "destination": ["demo-space", 0], "color": [1, 0.62, 0.24, 1]}},
      {"patchline": {"source": ["demo-space-fanout", 0], "destination": ["demo-out-space", 0], "color": [1, 0.62, 0.24, 1]}},
      {"patchline": {"source": ["demo-profile-engine", 5], "destination": ["demo-texture-fanout", 0], "color": [1, 0.62, 0.24, 1]}},
      {"patchline": {"source": ["demo-texture-fanout", 1], "destination": ["demo-texture", 0], "color": [1, 0.62, 0.24, 1]}},
      {"patchline": {"source": ["demo-texture-fanout", 0], "destination": ["demo-out-texture", 0], "color": [1, 0.62, 0.24, 1]}},
      {"patchline": {"source": ["demo-profile-engine", 6], "destination": ["demo-transform-fanout", 0], "color": [1, 0.62, 0.24, 1]}},
      {"patchline": {"source": ["demo-transform-fanout", 1], "destination": ["demo-transform", 0], "color": [1, 0.62, 0.24, 1]}},
      {"patchline": {"source": ["demo-transform-fanout", 0], "destination": ["demo-out-transform", 0], "color": [1, 0.62, 0.24, 1]}},

      {"patchline": {"source": ["demo-dict-unpack", 0], "destination": ["demo-state-set", 0], "color": [1, 0.62, 0.24, 1]}},
      {"patchline": {"source": ["demo-state-set", 0], "destination": ["demo-state", 0], "color": [1, 0.62, 0.24, 1]}},
      {"patchline": {"source": ["demo-dict-unpack", 1], "destination": ["demo-calibrated", 0], "color": [1, 0.62, 0.24, 1]}},
      {"patchline": {"source": ["demo-dict-unpack", 2], "destination": ["demo-tracking", 0], "color": [1, 0.62, 0.24, 1]}},
      {"patchline": {"source": ["demo-dict-unpack", 3], "destination": ["demo-zone", 0], "color": [1, 0.62, 0.24, 1]}},
      {"patchline": {"source": ["demo-dict-unpack", 5], "destination": ["demo-clutch", 0], "color": [1, 0.62, 0.24, 1]}},
      {"patchline": {"source": ["demo-dict-unpack", 6], "destination": ["demo-model", 0], "color": [1, 0.62, 0.24, 1]}},
      {"patchline": {"source": ["demo-dict-unpack", 7], "destination": ["demo-camera-ready", 0], "color": [1, 0.62, 0.24, 1]}},
      {"patchline": {"source": ["demo-dict-unpack", 8], "destination": ["demo-has-pose", 0], "color": [1, 0.62, 0.24, 1]}},
      {"patchline": {"source": ["demo-dict-unpack", 9], "destination": ["demo-sway", 0], "color": [1, 0.62, 0.24, 1]}},
      {"patchline": {"source": ["demo-dict-unpack", 10], "destination": ["demo-lean", 0], "color": [1, 0.62, 0.24, 1]}},
      {"patchline": {"source": ["demo-dict-unpack", 11], "destination": ["demo-shoulder", 0], "color": [1, 0.62, 0.24, 1]}},
      {"patchline": {"source": ["demo-dict-unpack", 12], "destination": ["demo-head", 0], "color": [1, 0.62, 0.24, 1]}},
      {"patchline": {"source": ["demo-dict-unpack", 13], "destination": ["demo-proximity", 0], "color": [1, 0.62, 0.24, 1]}},
      {"patchline": {"source": ["demo-dict-unpack", 14], "destination": ["demo-motion", 0], "color": [1, 0.62, 0.24, 1]}},

      {"patchline": {"source": ["demo-loadbang", 0], "destination": ["demo-init-trigger", 0], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["demo-init-trigger", 1], "destination": ["demo-init-profile", 0], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["demo-init-trigger", 0], "destination": ["demo-init-arm", 0], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["demo-init-profile", 0], "destination": ["demo-profile", 0], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["demo-init-arm", 0], "destination": ["demo-arm", 0], "color": [0.44, 0.72, 1, 1]}}
    ]
  }
}
