{
  "patcher": {
    "fileversion": 1,
    "appversion": {
      "major": 9,
      "minor": 1,
      "revision": 4,
      "architecture": "x64",
      "modernui": 1
    },
    "classnamespace": "box",
    "rect": [80, 80, 1180, 720],
    "gridsize": [15, 15],
    "openinpresentation": 1,
    "description": "Optional MIDI foot clutch with learn and device-loss safety.",
    "tags": "pose midi foot pedal clutch learn safety",
    "boxes": [
      {"box": {"id": "midi-title", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [40, 25, 560, 24], "text": "MT MIDI Clutch - optional foot control", "presentation": 1, "presentation_rect": [20, 16, 350, 24]}},
      {"box": {"id": "midi-note", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [40, 50, 900, 22], "text": "Device loss closes the clutch before reporting disconnect. Reconnection never opens it automatically.", "presentation": 1, "presentation_rect": [20, 42, 650, 22]}},
      {"box": {"id": "midi-device-label", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [40, 100, 100, 22], "text": "MIDI Device", "presentation": 1, "presentation_rect": [20, 82, 100, 22]}},
      {"box": {"id": "midi-device", "maxclass": "umenu", "numinlets": 1, "numoutlets": 3, "outlettype": ["int", "", ""], "items": [], "parameter_enable": 0, "patching_rect": [150, 100, 250, 22], "varname": "pose_midi_device", "hint": "Select the MIDI foot-controller input device", "presentation": 1, "presentation_rect": [125, 82, 250, 22]}},
      {"box": {"id": "midi-learn-label", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [430, 100, 70, 22], "text": "Learn", "presentation": 1, "presentation_rect": [410, 82, 50, 22]}},
      {"box": {"id": "midi-learn", "maxclass": "toggle", "numinlets": 1, "numoutlets": 1, "outlettype": ["int"], "parameter_enable": 0, "patching_rect": [500, 98, 24, 24], "varname": "pose_midi_learn", "hint": "Arm MIDI Learn; the next CC stores controller and channel", "presentation": 1, "presentation_rect": [465, 80, 24, 24]}},
      {"box": {"id": "midi-mode-label", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [560, 100, 100, 22], "text": "Pedal Mode", "presentation": 1, "presentation_rect": [520, 82, 90, 22]}},
      {"box": {"id": "midi-mode", "maxclass": "toggle", "numinlets": 1, "numoutlets": 1, "outlettype": ["int"], "parameter_enable": 0, "patching_rect": [665, 98, 24, 24], "varname": "pose_midi_mode", "hint": "Enable optional foot clutch; off restores the gate", "presentation": 1, "presentation_rect": [615, 80, 24, 24]}},

      {"box": {"id": "midi-info", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [150, 195, 60, 22], "text": "midiinfo"}},
      {"box": {"id": "midi-info-fanout", "maxclass": "newobj", "numinlets": 1, "numoutlets": 2, "outlettype": ["list", "list"], "patching_rect": [150, 235, 45, 22], "text": "t l l"}},
      {"box": {"id": "midi-refresh", "maxclass": "message", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [55, 195, 35, 22], "text": "-1"}},
      {"box": {"id": "midi-metro", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": ["bang"], "patching_rect": [55, 235, 80, 22], "text": "metro 1000"}},
      {"box": {"id": "midi-device-trigger", "maxclass": "newobj", "numinlets": 1, "numoutlets": 2, "outlettype": ["", ""], "patching_rect": [280, 195, 45, 22], "text": "t s s"}},
      {"box": {"id": "midi-port", "maxclass": "newobj", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [280, 235, 90, 22], "text": "prepend port"}},
      {"box": {"id": "midi-selected-device", "maxclass": "newobj", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [390, 235, 105, 22], "text": "prepend device"}},
      {"box": {"id": "midi-ctlin", "maxclass": "newobj", "numinlets": 1, "numoutlets": 3, "outlettype": ["int", "int", "int"], "patching_rect": [280, 285, 55, 22], "text": "ctlin"}},
      {"box": {"id": "midi-pack-cc", "maxclass": "newobj", "numinlets": 3, "numoutlets": 1, "outlettype": ["list"], "patching_rect": [280, 325, 85, 22], "text": "pack 0 0 0"}},
      {"box": {"id": "midi-learn-message", "maxclass": "newobj", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [500, 145, 95, 22], "text": "prepend learn"}},
      {"box": {"id": "midi-mode-trigger", "maxclass": "newobj", "numinlets": 1, "numoutlets": 5, "outlettype": ["int", "int", "int", "int", "int"], "patching_rect": [665, 145, 80, 22], "text": "t i i i i i"}},
      {"box": {"id": "midi-mode-select", "maxclass": "newobj", "numinlets": 1, "numoutlets": 2, "outlettype": ["bang", "bang"], "patching_rect": [770, 195, 55, 22], "text": "sel 0 1"}},
      {"box": {"id": "midi-mode-off-safe", "maxclass": "newobj", "numinlets": 1, "numoutlets": 2, "outlettype": ["int", "int"], "patching_rect": [735, 235, 50, 22], "text": "t 1 1"}},
      {"box": {"id": "midi-mode-on-safe", "maxclass": "newobj", "numinlets": 1, "numoutlets": 3, "outlettype": ["bang", "int", "int"], "patching_rect": [810, 235, 60, 22], "text": "t b 0 0"}},

      {"box": {"id": "midi-watch-js", "maxclass": "newobj", "numinlets": 4, "numoutlets": 4, "outlettype": ["", "", "", ""], "patching_rect": [390, 385, 320, 22], "text": "js Patcher:/../../javascript/mt_midi_device_watch.js", "varname": "pose_midi_watcher"}},
      {"box": {"id": "midi-cc-gate", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [390, 435, 45, 22], "text": "gate 1"}},
      {"box": {"id": "midi-threshold", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": ["int"], "patching_rect": [390, 475, 45, 22], "text": ">= 64"}},
      {"box": {"id": "midi-connected-gate", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [500, 435, 45, 22], "text": "gate 1"}},
      {"box": {"id": "midi-connected-select", "maxclass": "newobj", "numinlets": 1, "numoutlets": 2, "outlettype": ["bang", "bang"], "patching_rect": [500, 475, 55, 22], "text": "sel 0 1"}},
      {"box": {"id": "midi-disconnect-safe", "maxclass": "newobj", "numinlets": 1, "numoutlets": 2, "outlettype": ["int", "int"], "patching_rect": [475, 515, 50, 22], "text": "t 0 0"}},
      {"box": {"id": "midi-connected-one", "maxclass": "message", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [540, 515, 35, 22], "text": "1"}},
      {"box": {"id": "midi-learn-set", "maxclass": "newobj", "numinlets": 1, "numoutlets": 1, "outlettype": [""], "patching_rect": [650, 435, 75, 22], "text": "prepend set"}},

      {"box": {"id": "midi-loadbang", "maxclass": "newobj", "numinlets": 1, "numoutlets": 1, "outlettype": ["bang"], "patching_rect": [900, 100, 65, 22], "text": "loadbang"}},
      {"box": {"id": "midi-init-trigger", "maxclass": "newobj", "numinlets": 1, "numoutlets": 5, "outlettype": ["bang", "bang", "bang", "bang", "bang"], "patching_rect": [900, 145, 90, 22], "text": "t b b b b b"}},
      {"box": {"id": "midi-init-mode", "maxclass": "message", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [900, 195, 35, 22], "text": "0"}},
      {"box": {"id": "midi-init-learn", "maxclass": "message", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [945, 195, 35, 22], "text": "0"}},
      {"box": {"id": "midi-init-connected", "maxclass": "message", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [990, 195, 35, 22], "text": "1"}},
      {"box": {"id": "midi-init-clutch", "maxclass": "message", "numinlets": 2, "numoutlets": 1, "outlettype": [""], "patching_rect": [1035, 195, 35, 22], "text": "1"}},

      {"box": {"id": "midi-out-clutch", "maxclass": "outlet", "numinlets": 1, "numoutlets": 0, "patching_rect": [100, 625, 30, 30], "comment": "clutch 0/1"}},
      {"box": {"id": "midi-out-mode", "maxclass": "outlet", "numinlets": 1, "numoutlets": 0, "patching_rect": [300, 625, 30, 30], "comment": "pedal_mode 0/1"}},
      {"box": {"id": "midi-out-connected", "maxclass": "outlet", "numinlets": 1, "numoutlets": 0, "patching_rect": [500, 625, 30, 30], "comment": "pedal_connected 0/1"}},
      {"box": {"id": "midi-out-status", "maxclass": "outlet", "numinlets": 1, "numoutlets": 0, "patching_rect": [700, 625, 30, 30], "comment": "status symbol"}}
    ],
    "lines": [
      {"patchline": {"source": ["midi-refresh", 0], "destination": ["midi-info", 1], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["midi-metro", 0], "destination": ["midi-refresh", 0], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["midi-info", 0], "destination": ["midi-info-fanout", 0], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["midi-info-fanout", 1], "destination": ["midi-device", 0], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["midi-info-fanout", 0], "destination": ["midi-watch-js", 0], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["midi-device", 1], "destination": ["midi-device-trigger", 0], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["midi-device-trigger", 1], "destination": ["midi-port", 0], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["midi-device-trigger", 0], "destination": ["midi-selected-device", 0], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["midi-port", 0], "destination": ["midi-ctlin", 0], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["midi-selected-device", 0], "destination": ["midi-watch-js", 1], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["midi-ctlin", 2], "destination": ["midi-pack-cc", 2], "color": [1, 0.62, 0.24, 1]}},
      {"patchline": {"source": ["midi-ctlin", 1], "destination": ["midi-pack-cc", 1], "color": [1, 0.62, 0.24, 1]}},
      {"patchline": {"source": ["midi-ctlin", 0], "destination": ["midi-pack-cc", 0], "color": [1, 0.62, 0.24, 1]}},
      {"patchline": {"source": ["midi-pack-cc", 0], "destination": ["midi-watch-js", 2], "color": [1, 0.62, 0.24, 1]}},
      {"patchline": {"source": ["midi-learn", 0], "destination": ["midi-learn-message", 0], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["midi-learn-message", 0], "destination": ["midi-watch-js", 3], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["midi-watch-js", 3], "destination": ["midi-learn-set", 0], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["midi-learn-set", 0], "destination": ["midi-learn", 0], "color": [0.44, 0.72, 1, 1]}},

      {"patchline": {"source": ["midi-mode", 0], "destination": ["midi-mode-trigger", 0], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["midi-mode-trigger", 4], "destination": ["midi-cc-gate", 0], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["midi-mode-trigger", 3], "destination": ["midi-connected-gate", 0], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["midi-mode-trigger", 2], "destination": ["midi-metro", 0], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["midi-mode-trigger", 1], "destination": ["midi-mode-select", 0], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["midi-mode-trigger", 0], "destination": ["midi-out-mode", 0], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["midi-mode-select", 0], "destination": ["midi-mode-off-safe", 0], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["midi-mode-off-safe", 1], "destination": ["midi-out-clutch", 0], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["midi-mode-off-safe", 0], "destination": ["midi-out-connected", 0], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["midi-mode-select", 1], "destination": ["midi-mode-on-safe", 0], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["midi-mode-on-safe", 2], "destination": ["midi-out-clutch", 0], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["midi-mode-on-safe", 1], "destination": ["midi-out-connected", 0], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["midi-mode-on-safe", 0], "destination": ["midi-refresh", 0], "color": [0.44, 0.72, 1, 1]}},

      {"patchline": {"source": ["midi-watch-js", 0], "destination": ["midi-cc-gate", 1], "color": [1, 0.62, 0.24, 1]}},
      {"patchline": {"source": ["midi-cc-gate", 0], "destination": ["midi-threshold", 0], "color": [1, 0.62, 0.24, 1]}},
      {"patchline": {"source": ["midi-threshold", 0], "destination": ["midi-out-clutch", 0], "color": [1, 0.62, 0.24, 1]}},
      {"patchline": {"source": ["midi-watch-js", 1], "destination": ["midi-connected-gate", 1], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["midi-connected-gate", 0], "destination": ["midi-connected-select", 0], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["midi-connected-select", 0], "destination": ["midi-disconnect-safe", 0], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["midi-disconnect-safe", 1], "destination": ["midi-out-clutch", 0], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["midi-disconnect-safe", 0], "destination": ["midi-out-connected", 0], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["midi-connected-select", 1], "destination": ["midi-connected-one", 0], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["midi-connected-one", 0], "destination": ["midi-out-connected", 0], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["midi-watch-js", 2], "destination": ["midi-out-status", 0], "color": [0.44, 0.72, 1, 1]}},

      {"patchline": {"source": ["midi-loadbang", 0], "destination": ["midi-init-trigger", 0], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["midi-init-trigger", 4], "destination": ["midi-refresh", 0], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["midi-init-trigger", 3], "destination": ["midi-init-clutch", 0], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["midi-init-trigger", 2], "destination": ["midi-init-connected", 0], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["midi-init-trigger", 1], "destination": ["midi-init-learn", 0], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["midi-init-trigger", 0], "destination": ["midi-init-mode", 0], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["midi-init-clutch", 0], "destination": ["midi-out-clutch", 0], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["midi-init-connected", 0], "destination": ["midi-out-connected", 0], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["midi-init-learn", 0], "destination": ["midi-learn", 0], "color": [0.44, 0.72, 1, 1]}},
      {"patchline": {"source": ["midi-init-mode", 0], "destination": ["midi-mode", 0], "color": [0.44, 0.72, 1, 1]}}
    ]
  }
}
